### ISSUE TITLE
[FEATURE REQ] Script for install

### ISSUE THREAD

**Issue by ostermayer** [twofaktor/minibolt#2]
### What & why

An additional option for the more trusted setup could be a few "scripts" that prepopulate much of the commands for install and security settings.  Users still controll install of the ubuntu server but have easy of install and setup for many of the dependancies.  Although great education to setup each application many will opt for a more automated scripted install 
### How
Bash script to automate much of the ubuntu hardening

### Additional context
Also a separate set of script to automate the application installs

**Comment by twofaktor** [comment]
Hi, thanks for your suggestion, but, MiniBolt pretends to follow the same line as Raspibolt:

`We strive to give foolproof instructions. But the goal is also to do everything ourselves. Shortcuts that involve trusting someone else are not allowed

https://raspibolt.org/#target-audience = https://twofaktor.github.io/minibolt/#target-audience

If we do what you suggest, then MiniBolt will convert to Miniblitz, and that is not the intention.

Thanks anyway!
