### ISSUE TITLE
[SUPPORT] Assertion 'fclose_nointr(f) != -EBADF' for SSH remote access through Tor 

### ISSUE THREAD

**Issue by ywiyogo** [twofaktor/minibolt#45]
### Describe the bug

I did the instruction on this page  https://minibolt.info/guide/system/privacy.html#ssh-remote-access-through-tor-optional. I can have a ssh access with pubkey in my local network. The tor service runs good. However, running the `torify` or `torsocks` on my Linux laptop `torify ssh admin@xxxx....onion` throws warnings and assertion error:

```
1680094282 WARNING torsocks[38972]: [syscall] Unsupported syscall number 39. Denying the call (in tsocks_syscall() at syscall.c:604)
....
Assertion 'fclose_nointr(f) != -EBADF' failed at src/basic/fd-util.c:125, function safe_fclose(). Aborting.
Aborted (core dumped)
```

### Location in guide

Link to the corresponding page and section on <https://minibolt.info/guide/system/privacy.html#ssh-remote-access-through-tor-optional>

### Expected behavior

No error and a successful ssh connection to my minibolt

### Screenshots

none

### Environment

- Hardware platform: ARM64 Rockchip-rk3588
- Operating system: Armbian 23.02.2 Jammy 
- Version: Ubuntu 22.04.2 LTS

### Additional context

-

**Comment by twofaktor** [comment]
MiniBolt is for amd64 architecture. Follow MiniBolt guide step-by-step
