### ISSUE TITLE
[BUG] CoreLN failed to start

### ISSUE THREAD

**Issue by ostermayer** [twofaktor/minibolt#8]
### Describe the bug
After enabling and starting up CLN with 
$ sudo systemctl daemon-reload
$ sudo systemctl enable lightningd.service
$ sudo systemctl start lightningd.service

I have been unsuccesful getting CLN to launch.  Below is the log error:

Nov 04 22:51:09 minibolt sh[64109]: Lost connection to the RPC socket.
Nov 04 22:51:09 minibolt systemd[1]: lightningd.service: Failed with result 'core-dump'.''

### Location in guide

[Link to the corresponding page and section on <https://twofaktor.github.io/minibolt/>](https://github.com/twofaktor/minibolt/blob/main/guide/bonus/lightning/cln.md)

### Environment

- Hardware platform: [e.g. Intel i5]
- Operating system: [e.g, Ubuntu Server ]

**Comment by twofaktor** [comment]
Could you show me more previous logs?

**Comment by ostermayer** [comment]
sorry. will try and recreate at another time. unfortunately i no longer
have the logs from that machine
